version: '3.4'

services:
  study-dotnetcore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44322
    ports:
      - "51896:80"
      - "44322:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - study-sqlserver

  study-sqlserver:
    volumes:
      - .\study-sqlserver\mssql:/var/opt/mssql
    ports:
      - "1433:1433"