FROM microsoft/mssql-server-linux:2017-latest
EXPOSE 1433

ENV ACCEPT_EULA="Y" \
	SA_PASSWORD="Password@2018" \
	ACCEPT_EULA="Y" \
	MSSQL_PID="Developer" \
	MSSQL_LCID=1041 \
	MSSQL_COLLATION="Japanese_CI_AS"